/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Tarde
 */
public class PantallaInicial extends javax.swing.JFrame {
    
    private int [][] matriz;
    public PantallaInicial() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(203,224,233));
        setLocationRelativeTo(null);
        setResizable(false);
        jPanel1.setOpaque(false);
        matriz = new int[5][5];
        
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                int numeroAleatorio;
                do {
                    numeroAleatorio = (int) (Math.random() * 75) + 1;
                } while (numeroRepetido(matriz, numeroAleatorio));
                matriz[i][j] = numeroAleatorio;
            }
        }
        jTextFiel00.setText(String.valueOf(matriz[0][0]));
        jTextFiel01.setText(String.valueOf(matriz[0][1]));
        jTextFiel02.setText(String.valueOf(matriz[0][2]));
        jTextFiel03.setText(String.valueOf(matriz[0][3]));
        jTextFiel04.setText(String.valueOf(matriz[0][4]));

        jTextFiel10.setText(String.valueOf(matriz[1][0]));
        jTextFiel11.setText(String.valueOf(matriz[1][1]));
        jTextFiel12.setText(String.valueOf(matriz[1][2]));
        jTextFiel13.setText(String.valueOf(matriz[1][3]));
        jTextFiel14.setText(String.valueOf(matriz[1][4]));

        jTextFiel20.setText(String.valueOf(matriz[2][0]));
        jTextFiel21.setText(String.valueOf(matriz[2][1]));
        jTextFiel22.setText(String.valueOf(matriz[2][2]));
        jTextFiel23.setText(String.valueOf(matriz[2][3]));
        jTextFiel24.setText(String.valueOf(matriz[2][4]));

        jTextFiel30.setText(String.valueOf(matriz[3][0]));
        jTextFiel31.setText(String.valueOf(matriz[3][1]));
        jTextFiel32.setText(String.valueOf(matriz[3][2]));
        jTextFiel33.setText(String.valueOf(matriz[3][3]));
        jTextFiel34.setText(String.valueOf(matriz[3][4]));

        jTextFiel40.setText(String.valueOf(matriz[4][0]));
        jTextFiel41.setText(String.valueOf(matriz[4][1]));
        jTextFiel42.setText(String.valueOf(matriz[4][2]));
        jTextFiel43.setText(String.valueOf(matriz[4][3]));
        jTextFiel44.setText(String.valueOf(matriz[4][4]));
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBingo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFiel00 = new javax.swing.JTextField();
        jTextFiel01 = new javax.swing.JTextField();
        jTextFiel02 = new javax.swing.JTextField();
        jTextFiel03 = new javax.swing.JTextField();
        jTextFiel04 = new javax.swing.JTextField();
        jTextFiel10 = new javax.swing.JTextField();
        jTextFiel11 = new javax.swing.JTextField();
        jTextFiel12 = new javax.swing.JTextField();
        jTextFiel13 = new javax.swing.JTextField();
        jTextFiel14 = new javax.swing.JTextField();
        jTextFiel20 = new javax.swing.JTextField();
        jTextFiel21 = new javax.swing.JTextField();
        jTextFiel22 = new javax.swing.JTextField();
        jTextFiel23 = new javax.swing.JTextField();
        jTextFiel24 = new javax.swing.JTextField();
        jTextFiel30 = new javax.swing.JTextField();
        jTextFiel31 = new javax.swing.JTextField();
        jTextFiel32 = new javax.swing.JTextField();
        jTextFiel33 = new javax.swing.JTextField();
        jTextFiel34 = new javax.swing.JTextField();
        jTextFiel40 = new javax.swing.JTextField();
        jTextFiel41 = new javax.swing.JTextField();
        jTextFiel42 = new javax.swing.JTextField();
        jTextFiel43 = new javax.swing.JTextField();
        jTextFiel44 = new javax.swing.JTextField();
        jButtonGenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBingo.setFont(new java.awt.Font("MV Boli", 0, 48)); // NOI18N
        jLabelBingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBingo.setText("BINGO");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cartón:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 502, -1));

        jTextFiel00.setEditable(false);
        jTextFiel00.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFiel00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiel00ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFiel00, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 71, 66));

        jTextFiel01.setEditable(false);
        jTextFiel01.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 71, 66));

        jTextFiel02.setEditable(false);
        jTextFiel02.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 71, 66));

        jTextFiel03.setEditable(false);
        jTextFiel03.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 71, 66));

        jTextFiel04.setEditable(false);
        jTextFiel04.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 71, 66));

        jTextFiel10.setEditable(false);
        jTextFiel10.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 71, 66));

        jTextFiel11.setEditable(false);
        jTextFiel11.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 71, 66));

        jTextFiel12.setEditable(false);
        jTextFiel12.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 71, 66));

        jTextFiel13.setEditable(false);
        jTextFiel13.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 71, 66));

        jTextFiel14.setEditable(false);
        jTextFiel14.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 71, 66));

        jTextFiel20.setEditable(false);
        jTextFiel20.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 71, 66));

        jTextFiel21.setEditable(false);
        jTextFiel21.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 71, 66));

        jTextFiel22.setEditable(false);
        jTextFiel22.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 71, 66));

        jTextFiel23.setEditable(false);
        jTextFiel23.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 71, 66));

        jTextFiel24.setEditable(false);
        jTextFiel24.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 71, 66));

        jTextFiel30.setEditable(false);
        jTextFiel30.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 71, 66));

        jTextFiel31.setEditable(false);
        jTextFiel31.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 71, 66));

        jTextFiel32.setEditable(false);
        jTextFiel32.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 71, 66));

        jTextFiel33.setEditable(false);
        jTextFiel33.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 71, 66));

        jTextFiel34.setEditable(false);
        jTextFiel34.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 71, 66));

        jTextFiel40.setEditable(false);
        jTextFiel40.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 71, 66));

        jTextFiel41.setEditable(false);
        jTextFiel41.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 71, 66));

        jTextFiel42.setEditable(false);
        jTextFiel42.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 71, 66));

        jTextFiel43.setEditable(false);
        jTextFiel43.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 71, 66));

        jTextFiel44.setEditable(false);
        jTextFiel44.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jTextFiel44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextFiel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 71, 66));

        jButtonGenerar.setText("Generar número");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Último número:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBingo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonGenerar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelBingo)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFiel00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiel00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFiel00ActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        int numeroGenerado = (int) (Math.random() * 75) + 1;
        jLabel3.setText("Último número: "+numeroGenerado);
        comprobarNumero(matriz, numeroGenerado);
            
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBingo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFiel00;
    private javax.swing.JTextField jTextFiel01;
    private javax.swing.JTextField jTextFiel02;
    private javax.swing.JTextField jTextFiel03;
    private javax.swing.JTextField jTextFiel04;
    private javax.swing.JTextField jTextFiel10;
    private javax.swing.JTextField jTextFiel11;
    private javax.swing.JTextField jTextFiel12;
    private javax.swing.JTextField jTextFiel13;
    private javax.swing.JTextField jTextFiel14;
    private javax.swing.JTextField jTextFiel20;
    private javax.swing.JTextField jTextFiel21;
    private javax.swing.JTextField jTextFiel22;
    private javax.swing.JTextField jTextFiel23;
    private javax.swing.JTextField jTextFiel24;
    private javax.swing.JTextField jTextFiel30;
    private javax.swing.JTextField jTextFiel31;
    private javax.swing.JTextField jTextFiel32;
    private javax.swing.JTextField jTextFiel33;
    private javax.swing.JTextField jTextFiel34;
    private javax.swing.JTextField jTextFiel40;
    private javax.swing.JTextField jTextFiel41;
    private javax.swing.JTextField jTextFiel42;
    private javax.swing.JTextField jTextFiel43;
    private javax.swing.JTextField jTextFiel44;
    // End of variables declaration//GEN-END:variables

private boolean numeroRepetido(int[][] matriz, int numero) {
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                if (matriz[i][j] == numero) {
                    return true;
                }
            }
        }
        return false;
    }

private void comprobarNumero(int[][] matriz, int numero) {
    for (int i = 0; i < matriz.length; i++) {
        for (int j = 0; j < matriz[i].length; j++) {
            if (matriz[i][j] == numero) {
                marcarCasilla(i, j);
                if (comprobarVictoria()) {
                    JOptionPane.showMessageDialog(this, "¡Has ganado el Bingo!", "Victoria", JOptionPane.INFORMATION_MESSAGE);
                    jButtonGenerar.setEnabled(false);
                }
                return;
            }
        }
    }
}


private void marcarCasilla(int fila, int columna) {
   JTextField campo = obtenerCampo(fila, columna);
    if (campo != null) {
        campo.setText("X");
        campo.setFont(new java.awt.Font("MV Boli", java.awt.Font.BOLD, 24));
        campo.setForeground(java.awt.Color.RED);
    }
}

private JTextField obtenerCampo(int fila, int columna) {
    JTextField[][] campos = {
        {jTextFiel00, jTextFiel01, jTextFiel02, jTextFiel03, jTextFiel04},
        {jTextFiel10, jTextFiel11, jTextFiel12, jTextFiel13, jTextFiel14},
        {jTextFiel20, jTextFiel21, jTextFiel22, jTextFiel23, jTextFiel24},
        {jTextFiel30, jTextFiel31, jTextFiel32, jTextFiel33, jTextFiel34},
        {jTextFiel40, jTextFiel41, jTextFiel42, jTextFiel43, jTextFiel44}
    };
    
    return campos[fila][columna];
}

private boolean comprobarVictoria() {
    for (int i = 0; i < matriz.length; i++) {
        boolean filaCompleta = true;
        for (int j = 0; j < matriz[i].length; j++) {
            if (!campoTachado(i, j)) {
                filaCompleta = false;
                break;
            }
        }
        if (filaCompleta) {
            return true; 
        }
    }

    for (int j = 0; j < matriz[0].length; j++) {
        boolean columnaCompleta = true;
        for (int i = 0; i < matriz.length; i++) {
            if (!campoTachado(i, j)) {
                columnaCompleta = false;
                break;
            }
        }
        if (columnaCompleta) {
            return true;
        }
    }

    boolean diagonalPrimera = true;
    for (int i = 0; i < matriz.length; i++) {
        if (!campoTachado(i, i)) {
            diagonalPrimera = false;
            break;
        }
    }
    if (diagonalPrimera) {
        return true;
    }

    boolean diagonalSegunda = true;
    for (int i = 0; i < matriz.length; i++) {
        if (!campoTachado(i, matriz.length - 1 - i)) {
            diagonalSegunda = false;
            break;
        }
    }
    if (diagonalSegunda) {
        return true;
    }

    return false;
}

private boolean campoTachado(int fila, int columna) {
    JTextField campo = obtenerCampo(fila, columna);
    return campo.getText().equals("X");
}

}
