/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act2ut7;

import java.io.File;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author Tarde
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        ponLaAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIntro = new javax.swing.JButton();
        jButtonAcerca = new javax.swing.JButton();
        jButtonFunciones = new javax.swing.JButton();
        jButtonInstalacion = new javax.swing.JButton();
        jButtonInterfaz = new javax.swing.JButton();
        jButtonSoluciones = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonIntro.setText("Introducción");

        jButtonAcerca.setText("Acerca de");

        jButtonFunciones.setText("Funciones");

        jButtonInstalacion.setText("Instalacion");

        jButtonInterfaz.setText("Interfaz");

        jButtonSoluciones.setText("Soluciones");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuAyuda.setText("Ayuda");

        jMenuItem1.setText("Mostrar ayuda");
        jMenuAyuda.add(jMenuItem1);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIntro)
                    .addComponent(jButtonInstalacion))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAcerca)
                    .addComponent(jButtonInterfaz))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFunciones)
                    .addComponent(jButtonSoluciones))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIntro)
                    .addComponent(jButtonAcerca)
                    .addComponent(jButtonFunciones))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInstalacion)
                    .addComponent(jButtonInterfaz)
                    .addComponent(jButtonSoluciones))
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcerca;
    private javax.swing.JButton jButtonFunciones;
    private javax.swing.JButton jButtonInstalacion;
    private javax.swing.JButton jButtonInterfaz;
    private javax.swing.JButton jButtonIntro;
    private javax.swing.JButton jButtonSoluciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void ponLaAyuda() {
        try{
            File fichero = new File("help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpOnButton(jMenuItem1, "introduccion", helpset);
            hb.enableHelpKey(getRootPane(), "introduccion", helpset);
            hb.enableHelpKey(jButtonIntro, "introduccion", helpset);
            hb.enableHelpKey(jButtonAcerca, "acerca", helpset);
            hb.enableHelpKey(jButtonInstalacion, "instalacion", helpset);
            hb.enableHelpKey(jButtonSoluciones, "soluciones", helpset);
            hb.enableHelpKey(jButtonInterfaz, "interfaz", helpset);
            hb.enableHelpKey(jButtonFunciones, "funciones", helpset);
            hb.enableHelpOnButton(jButtonIntro, "introduccion", helpset);
            hb.enableHelpOnButton(jButtonAcerca, "acerca", helpset);
            hb.enableHelpOnButton(jButtonInstalacion, "instalacion", helpset);
            hb.enableHelpOnButton(jButtonSoluciones, "soluciones", helpset);
            hb.enableHelpOnButton(jButtonInterfaz, "interfaz", helpset);
            hb.enableHelpOnButton(jButtonFunciones, "funciones", helpset);
        }catch(Exception e){
            e.printStackTrace();
        }
            
        
    }
}
