/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Tarde
 */
public class Altas extends javax.swing.JFrame {

    PantallaInicial parent;
    AltaProveedor altaP;
    /**
     * Creates new form Altas
     */
    public Altas(PantallaInicial parent) {
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Altas");
        this.altaP = new AltaProveedor(this);
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/imgs/Logo.png")).getImage());
        jPanelImagenBasico1.setRutaImagen("/gui/imgs/Guarida.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagenBasico1 = new jpanelimagenbasico.jPanelImagenBasico();
        jLabel1 = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonProveedores = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(545, 386));
        setMinimumSize(new java.awt.Dimension(545, 386));

        jLabel1.setFont(new java.awt.Font("Miriam Mono CLM", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Altas");

        jPanelBotones.setLayout(new java.awt.GridLayout(2, 2));

        jButtonProveedores.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/proveedor.png"))); // NOI18N
        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveedoresActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonProveedores);

        jButtonClientes.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/revision.png"))); // NOI18N
        jButtonClientes.setText("Clientes");
        jPanelBotones.add(jButtonClientes);

        jButtonProductos.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/paquete.png"))); // NOI18N
        jButtonProductos.setText("Productos");
        jPanelBotones.add(jButtonProductos);

        jButtonSalir.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/salida (1).png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonSalir);

        javax.swing.GroupLayout jPanelImagenBasico1Layout = new javax.swing.GroupLayout(jPanelImagenBasico1);
        jPanelImagenBasico1.setLayout(jPanelImagenBasico1Layout);
        jPanelImagenBasico1Layout.setHorizontalGroup(
            jPanelImagenBasico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenBasico1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelImagenBasico1Layout.setVerticalGroup(
            jPanelImagenBasico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenBasico1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenBasico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenBasico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
        altaP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBotones;
    private jpanelimagenbasico.jPanelImagenBasico jPanelImagenBasico1;
    // End of variables declaration//GEN-END:variables
}
