/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarde
 */
public class PantallaInicial extends javax.swing.JFrame {
    boolean clave = false;
    Altas a = new Altas(this);
    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicial() {
        initComponents();
        jTextFieldClave.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Logística");
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/imgs/Logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomUsuario = new javax.swing.JTextField();
        jLabelNomUsuario = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jPanelClave = new javax.swing.JPanel();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jTextFieldClave = new javax.swing.JTextField();
        jButtonMostrarClave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(652, 511));
        setMinimumSize(new java.awt.Dimension(652, 511));

        jTextFieldNomUsuario.setFont(new java.awt.Font("Miriam Mono CLM", 0, 14)); // NOI18N

        jLabelNomUsuario.setFont(new java.awt.Font("Miriam Mono CLM", 0, 14)); // NOI18N
        jLabelNomUsuario.setText("Nombre de usuario:");

        jLabelClave.setFont(new java.awt.Font("Miriam Mono CLM", 0, 14)); // NOI18N
        jLabelClave.setText("Clave:");

        jPanelClave.setLayout(new java.awt.CardLayout());
        jPanelClave.add(jPasswordFieldClave, "card3");
        jPanelClave.add(jTextFieldClave, "card2");

        jButtonMostrarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/ojo-abierto.png"))); // NOI18N
        jButtonMostrarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarClaveActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout());

        jButtonLimpiar.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/barriendo.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar);

        jButtonLogin.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/puerta-abierta.png"))); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);

        jButtonSalir.setFont(new java.awt.Font("Miriam Mono CLM", 1, 14)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/salida.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/224-2246823_pokemon-team-rocket-team-rocket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomUsuario)
                            .addComponent(jLabelClave))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelClave, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMostrarClave)
                                .addGap(9, 9, 9)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomUsuario))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelClave)
                    .addComponent(jButtonMostrarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarClaveActionPerformed
        if(!clave){
            jTextFieldClave.setText(new String(jPasswordFieldClave.getPassword()));
            jPasswordFieldClave.setVisible(false);
            jTextFieldClave.setVisible(true);
            jButtonMostrarClave.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/ojo.png")));
            clave = true;
        }
        else{
            jPasswordFieldClave.setText(jTextFieldClave.getText());
            jTextFieldClave.setVisible(false);
            jPasswordFieldClave.setVisible(true);
            jButtonMostrarClave.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/ojo-abierto.png")));
            clave = false;
        
        }
    }//GEN-LAST:event_jButtonMostrarClaveActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if(!clave){
            jTextFieldClave.setText(new String(jPasswordFieldClave.getPassword()));
        }else{
            jPasswordFieldClave.setText(jTextFieldClave.getText());
        }
        
        if(validarEntradas()){
            this.setVisible(false);
            a.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldClave.setText("");
        jTextFieldNomUsuario.setText("");
        jPasswordFieldClave.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonMostrarClave;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelNomUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelClave;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JTextField jTextFieldClave;
    private javax.swing.JTextField jTextFieldNomUsuario;
    // End of variables declaration//GEN-END:variables


    private boolean validarEntradas(){
        if(jPasswordFieldClave.getPassword().equals("") || (jTextFieldNomUsuario.getText().isEmpty()) || jTextFieldClave.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No puede haber campos en blanco", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(!jTextFieldNomUsuario.getText().matches("^[a-zA-Z]*$")){
            JOptionPane.showMessageDialog(this, "El nombre de usuario no puede contener números", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
        
    }
    
}
