CREATE OR REPLACE TYPE T_DEP AS OBJECT (
DEPT_NO INT,
DNOMBRE VARCHAR2(15),
LOC VARCHAR2(15));

COMMIT;

CREATE OR REPLACE TYPE T_EMPLE AS OBJECT(
EMP_NO INT,
APELLIDO VARCHAR2(10),
OFICIO VARCHAR2(10),
DIR INT,
FECHA_ALT DATE,
SALARIO FLOAT,
COMISION FLOAT,
DEPT_NO T_DEP);

CREATE TYPE V_EMPLE AS VARRAY(20) OF T_EMPLE;

CREATE TABLE TAB_DEP(
EMPLEADO V_EMPLE,
DEPARTAMENTO T_DEP);

CREATE OR REPLACE PROCEDURE MIS_EMPLEADOS AS

    EMPLE_DEP_VENTAS V_EMPLE;
    
    EMPLE_DEP_COMPRAS V_EMPLE;
    
    DEPA NUMBER;
    
BEGIN
    
    FOR DEPA IN (SELECT DEPT_NO FROM DEPARTAMENTOS)
        LOOP
            FOR j IN 1..EMPLEADOS.COUNT
                LOOP
                  --  INSERT TAB_DEP()
                END LOOP;    
        END LOOP;
    

END MIS_EMPLEADOS;