package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alejandro Sánchez Gil
 */
public class PantallaInicial extends javax.swing.JFrame {
    //Creamos una instancia de las 2 pantallas de la aplicación.
    Usuario user = new Usuario(this);
    PantallaSecundaria pantalla = new PantallaSecundaria(this, user);
    
    
    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicial() {
        initComponents();
        //Establecemos cambios visuales y decorados.
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/imgs/centro-de-juegos.png")).getImage());
        jPanel1.setBackground(new java.awt.Color(180, 211, 178));
        jPanel2.setOpaque(false);
        jButtonEspana.setBackground(new java.awt.Color(144, 168, 142));
        jButtonIngles.setBackground(new java.awt.Color(144, 168, 142));
        jPanel3.setBackground(new java.awt.Color(180, 211, 178));
        jButtonEntrar.setBackground(new java.awt.Color(144, 168, 142));
        jButtonLimpiar.setBackground(new java.awt.Color(144, 168, 142));
        jButtonSalir.setBackground(new java.awt.Color(144, 168, 142));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelIdioma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEspana = new javax.swing.JButton();
        jButtonIngles = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonEntrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(682, 437));

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/centro-de-juegos (2).png"))); // NOI18N

        jLabelInicio.setFont(new java.awt.Font("Reem Kufi", 1, 24)); // NOI18N
        jLabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInicio.setText("INICIO DE SESIÓN");

        jLabelNombre.setFont(new java.awt.Font("Reem Kufi", 1, 14)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Nombre de usuario:");

        jLabelPass.setFont(new java.awt.Font("Reem Kufi", 1, 14)); // NOI18N
        jLabelPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPass.setText("Contraseña:");

        jLabelIdioma.setFont(new java.awt.Font("Reem Kufi", 1, 14)); // NOI18N
        jLabelIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdioma.setText("Idioma:");

        jPanel2.setLayout(new java.awt.GridLayout());

        jButtonEspana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/spain25.png"))); // NOI18N
        jButtonEspana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspanaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEspana);

        jButtonIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/usa25.png"))); // NOI18N
        jButtonIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInglesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonIngles);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButtonEntrar.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEntrar);

        jButtonLimpiar.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLimpiar);

        jButtonSalir.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSalir);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabelLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelIdioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInicio)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPass)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Función del botón salir.
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed
    //Función del botón cambio de idioma a Español.
    private void jButtonEspanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspanaActionPerformed
        setSpanish();
    }//GEN-LAST:event_jButtonEspanaActionPerformed
    //Función del botón cambio de idioma a Inglés.
    private void jButtonInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInglesActionPerformed
        setEnglish();
    }//GEN-LAST:event_jButtonInglesActionPerformed
    //Función del botón Limpiar.
    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed
    //Función del botón entrada.
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        //Tras comprobar que las entradas son válidas.
        if(entradaValida()){
            //Establece el nombre de usuario y la contraseña para revisarlo posteriormente.
            user.setPass(new String(jPasswordField1.getPassword()));
            user.setNomUsu(jTextField1.getText());
            this.setVisible(false);
            //Abrimos la segunda pantalla.
            pantalla.setVisible(true);
        }else{
            //En caso de que no se cumpla.
            JOptionPane.showMessageDialog(this,"Los campos no pueden estar vacíos" ,"Error" ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonEspana;
    private javax.swing.JButton jButtonIngles;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelIdioma;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    //Método que cambia el idioma a Español.
    private void setSpanish() {
        jButtonEntrar.setText("Entrar");
        jButtonLimpiar.setText("Limpiar");
        jButtonSalir.setText("Salir");
        jLabelIdioma.setText("Idioma:");
        jLabelInicio.setText("INICIO DE SESIÓN");
        jLabelNombre.setText("Nombre de usuario:");
        jLabelPass.setText("Contraseña:");
        //Estos métodos sirven para cambiar el idioma en el resto de pantallas de la aplicación.
        pantalla.actualizarIdioma(true);
        user.actualizarIdioma(true);
    }
    //Método que cambia el idioma a Inglés
    private void setEnglish() {
        jButtonEntrar.setText("Login");
        jButtonLimpiar.setText("Clean");
        jButtonSalir.setText("Exit");
        jLabelIdioma.setText("Language:");
        jLabelInicio.setText("SIGN IN");
        jLabelNombre.setText("Username:");
        jLabelPass.setText("Password:");
        pantalla.actualizarIdioma(false);
        user.actualizarIdioma(false);
    }
    //Método que comprueba si las entradas son válidas. 
    //Considero como válido cualquier cosa, mientras no este vacío puedes tener un nombre de usuario numérico si lo deseas.
    private boolean entradaValida(){
        if(jTextField1.getText().equals("") || jPasswordField1.getPassword().length==0){
            return false;
        }
        return true;
    }
    
}

