/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.applet.AudioClip;
import javax.swing.ImageIcon;

/**
 *
 * @author Alejandro Sánchez Gil
 */
public class PantallaSecundaria extends javax.swing.JFrame {
    boolean playing = false;
    private PantallaInicial parent;
    private Usuario user;
    AudioClip mantra;
    AudioClip six;
    
    /**
     * Creates new form PantallaSecundaria
     */
    public PantallaSecundaria(PantallaInicial parent, Usuario user) {
        this.user = user;
        initComponents();
        this.parent = parent;
        this.setIconImage(new ImageIcon(getClass().getResource("/gui/imgs/reproductor-de-musica.png")).getImage());
        getContentPane().setBackground(new java.awt.Color(121, 210, 230));
        mantra = java.applet.Applet.newAudioClip(getClass().getResource("/audio/mantra.wav"));
        six = java.applet.Applet.newAudioClip(getClass().getResource("/audio/six.wav"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelReproductor = new javax.swing.JLabel();
        jLabelCanciones = new javax.swing.JLabel();
        jRadioButtonMantra = new javax.swing.JRadioButton();
        jRadioButtonSix = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelReproductor.setFont(new java.awt.Font("Reem Kufi", 1, 24)); // NOI18N
        jLabelReproductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReproductor.setText("REPRODUCTOR MP3");

        jLabelCanciones.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jLabelCanciones.setText("Mis canciones:");

        buttonGroup1.add(jRadioButtonMantra);
        jRadioButtonMantra.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jRadioButtonMantra.setSelected(true);
        jRadioButtonMantra.setText("Mantra Song");

        buttonGroup1.add(jRadioButtonSix);
        jRadioButtonSix.setFont(new java.awt.Font("Reem Kufi", 0, 14)); // NOI18N
        jRadioButtonSix.setText("Six Theorem");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/play.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/musica.png"))); // NOI18N

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/usuario.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUsuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuUsuario);

        jMenuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/bloquear.png"))); // NOI18N
        jMenuCerrar.setText("Cerrar Sesión");
        jMenuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelCanciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSix)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonMantra)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel3)))))
                .addContainerGap(234, Short.MAX_VALUE))
            .addComponent(jLabelReproductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReproductor)
                .addGap(51, 51, 51)
                .addComponent(jLabelCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMantra)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSix)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCerrarMouseClicked
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_jMenuCerrarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(jRadioButtonMantra.isSelected()){
            if(!playing){
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/detener.png")));
            mantra.play();
            playing = true;
            }else{
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/play.png")));
                mantra.stop();
                playing = false;
            }  
            
        }
        
        if(jRadioButtonSix.isSelected()){
            if(!playing){
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/detener.png")));
            six.play();
            playing = true;
            }else{
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/play.png")));
                six.stop();
                playing = false;
            }
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jMenuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUsuarioMouseClicked
        user.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCanciones;
    private javax.swing.JLabel jLabelReproductor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCerrar;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JRadioButton jRadioButtonMantra;
    private javax.swing.JRadioButton jRadioButtonSix;
    // End of variables declaration//GEN-END:variables

    public void actualizarIdioma(boolean spanish){
        if(spanish){
            jMenuUsuario.setText("Usuario");
            jMenuCerrar.setText("Cerrar Sesión");
            jLabelCanciones.setText("Mis canciones:");
            jLabelReproductor.setText("Reproductor MP3");
        }else{
            jMenuUsuario.setText("User");
            jMenuCerrar.setText("Logout");
            jLabelCanciones.setText("My songs:");
            jLabelReproductor.setText("MP3 Player");
        }
    }

}
