/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Sánchez Gil
 */
public class PantallaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicial
     */
    //Clase PantallaInicial con los métodos "initComponents()" que inicia todos los componentes de la aplicación y "getContentPane().setBackground" para cambiar el color
    //del fondo de la aplicación.
    public PantallaInicial() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(203, 224, 233));
        ponLaAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNivel = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxNivel = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelTorneo = new javax.swing.JLabel();
        jLabelBuscaminasLogo = new javax.swing.JLabel();
        jLabelLogoS = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("FORMULARIO DE REGISTRO");

        jLabelNombre.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Nombre:");

        jLabelApellidos.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApellidos.setText("Apellidos:");

        jLabelEdad.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabelEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEdad.setText("Edad:");

        jLabelEmail.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmail.setText("Email:");

        jLabelNivel.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabelNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivel.setText("Nivel de habilidad:");

        jTextFieldNombre.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldApellidos.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N

        jTextFieldEdad.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N

        jTextFieldEmail.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N

        jComboBoxNivel.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Amateur", "Profesional" }));

        jPanel1.setBackground(new java.awt.Color(203, 224, 243));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButtonRegistrar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonRegistrar.setText("Registrarse");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar);

        jButtonBorrar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorrar);

        jButtonSalir.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);

        jLabelTorneo.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelTorneo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTorneo.setText("TORNEO BUSCAMINAS EXPO SÁNCHEZ");

        jLabelBuscaminasLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/reescaladaBuscaminas.png"))); // NOI18N

        jLabelLogoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/reescaladaLogo.png"))); // NOI18N

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Mostrar Ayuda");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscaminasLogo)
                .addGap(51, 51, 51)
                .addComponent(jLabelLogoS)
                .addGap(278, 278, 278))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellidos)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelEdad)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelNivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTorneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBuscaminasLogo)
                    .addComponent(jLabelLogoS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelApellidos)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelEdad)
                        .addGap(34, 34, 34)
                        .addComponent(jLabelEmail)
                        .addGap(34, 34, 34)
                        .addComponent(jLabelNivel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    //Método ActionPerformed que tras haberse activado el ActionListener del botón "Registrar" se ejecutarán las siguientes ordenes.
    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        //Comprobamos si las entradas son válidas con el método "validarEntradas()".
        if(validarEntradas()){
            //En caso de que sea true, nos lanza un mensaje que nos indica un registro satisfactorio.
            JOptionPane.showMessageDialog(this, "Se ha registrado correctamente a "+jTextFieldNombre.getText()+
                " "+jTextFieldApellidos.getText()+" en el torneo en la dificultad: "+
                jComboBoxNivel.getSelectedItem(),"Registro completado",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed
    //Método ActionPerformed que tras haberse activado el ActionListener del botón "Salir" se ejecutarán las siguientes ordenes.
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Salida del sistema, es decir cierra la aplicación.
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed
    //Método ActionPerformed que tras haberse activado el ActionListener del botón "Limpiar" se ejecutarán las siguientes ordenes.
    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //Establece todos los campos en los que se puede escribir a vacío y devuelve el nivel a "Principiante" que es el primer valor.
        jTextFieldApellidos.setText("");
        jTextFieldNombre.setText("");
        jTextFieldEdad.setText("");
        jTextFieldEmail.setText("");
        jComboBoxNivel.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    //Método para validar las entradas del usuario.
    private boolean validarEntradas(){
        //Comprueba que el nombre no esté vacío y en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(jTextFieldNombre.getText().equals(null)||jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Error, el nombre no puede estar vacío", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //Comprueba que el apellido no esté vacío y en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(jTextFieldApellidos.getText().equals(null)||jTextFieldApellidos.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Error, el apellido no puede estar vacío", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //Comprueba que la edad no esté vacío y en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(jTextFieldEdad.getText().equals(null)||jTextFieldEdad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Error, la edad no puede estar vacía", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //Comprueba que la edad sea un número y en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(!jTextFieldEdad.getText().matches("2[01]?\\d|[1-9]?\\d")){
            JOptionPane.showMessageDialog(this, "Error, la edad debe ser un número", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //Comprueba que el email no esté vacío y en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(jTextFieldEmail.getText().equals(null)||jTextFieldEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Error, el email no puede estar vacío", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //Comprueba que el email contenga "@" y ".", en caso contrario lanza un mensaje de error y devuelve falso como valor.
        if(!jTextFieldEmail.getText().contains("@")||!jTextFieldEmail.getText().contains(".")){
            JOptionPane.showMessageDialog(this, "Error, introduce un dominio de email correcto", "Error.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxNivel;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelBuscaminasLogo;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogoS;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTorneo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables


    private void ponLaAyuda() {
        try {
            File fichero = new File("help"+File.separator+"help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpOnButton(jMenuItem1, "introduccion", helpset);
            hb.enableHelpKey(getRootPane(), "introduccion", helpset);
            
           
        } catch (MalformedURLException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
