/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Sánchez Gil
 */
public class Personajes extends javax.swing.JDialog {
    private PantallaInicial pantalla;
    private String nombre;
    /**
     * Creates new form Personajes
     */
    public Personajes(java.awt.Frame parent, boolean modal, String nombre) {
        super(parent, modal);
        getContentPane().setBackground(new java.awt.Color(173, 216, 230));
        pantalla = (PantallaInicial)parent;
        this.nombre=nombre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPersonaje = new javax.swing.ButtonGroup();
        jLabelInfo = new javax.swing.JLabel();
        jRadioButtonTorre = new javax.swing.JRadioButton();
        jRadioButtonAlfil = new javax.swing.JRadioButton();
        jRadioButtonCaballo = new javax.swing.JRadioButton();
        jButtonConfimar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInfo.setFont(new java.awt.Font("Poor Richard", 3, 18)); // NOI18N
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("¿Qué personaje quieres ser?");

        buttonGroupPersonaje.add(jRadioButtonTorre);
        jRadioButtonTorre.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        jRadioButtonTorre.setText("Torre");

        buttonGroupPersonaje.add(jRadioButtonAlfil);
        jRadioButtonAlfil.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        jRadioButtonAlfil.setText("Alfil");

        buttonGroupPersonaje.add(jRadioButtonCaballo);
        jRadioButtonCaballo.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        jRadioButtonCaballo.setText("Caballo");
        jRadioButtonCaballo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonCaballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCaballoActionPerformed(evt);
            }
        });

        jButtonConfimar.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jButtonConfimar.setText("Confirmar");
        jButtonConfimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonConfimar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonTorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCaballo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAlfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonAlfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonCaballo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jButtonConfimar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCaballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCaballoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCaballoActionPerformed

    private void jButtonConfimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfimarActionPerformed
        if(jRadioButtonCaballo.isSelected()){
          int respuesta = JOptionPane.showConfirmDialog(this, nombre+" has elegido al caballo, muy buena elección, pero ¿Estás completamente seguro de tu elección?","Selección de personaje",JOptionPane.YES_NO_OPTION);
           if(respuesta == JOptionPane.YES_OPTION){
               JOptionPane.showMessageDialog(this, "Bienvenido a MathGames","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
           }
        }else if(jRadioButtonTorre.isSelected()){
            int respuesta = JOptionPane.showConfirmDialog(this, nombre+" has elegido a la torre, muy buena elección, pero ¿Estás completamente seguro de tu elección?","Selección de personaje",JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
               JOptionPane.showMessageDialog(this, "Bienvenido a MathGames","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
           }
        }else if(jRadioButtonAlfil.isSelected()){
            int respuesta = JOptionPane.showConfirmDialog(this, nombre+" has elegido al alfil, muy buena elección, pero ¿Estás completamente seguro de tu elección?","Selección de personaje",JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
               JOptionPane.showMessageDialog(this, "Bienvenido a MathGames","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
           }
        }else{
            JOptionPane.showMessageDialog(this, "Tienes que elegir un personaje","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfimarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Personajes dialog = new Personajes(new javax.swing.JFrame(), true,"nombre");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPersonaje;
    private javax.swing.JButton jButtonConfimar;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JRadioButton jRadioButtonAlfil;
    private javax.swing.JRadioButton jRadioButtonCaballo;
    private javax.swing.JRadioButton jRadioButtonTorre;
    // End of variables declaration//GEN-END:variables
}
