/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tresEnRaya;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarde
 */
public class PantallaInicial extends javax.swing.JFrame {

    private boolean turnoX = true;
    public PantallaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(414, 510));
        setMinimumSize(new java.awt.Dimension(414, 510));
        setPreferredSize(new java.awt.Dimension(414, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Turno del jugador: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 100));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, 100));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, 100));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 100));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 100));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 110, 100));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 100));

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, 100));

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, 100));

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(turnoX == true){
            jButton3.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton3.setEnabled(false);
            desactivarBoton(jButton3);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton3.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton3.setEnabled(false);
            desactivarBoton(jButton3);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(turnoX == true){
            jButton6.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton6.setEnabled(false);
            desactivarBoton(jButton6);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton6.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton6.setEnabled(false);
            desactivarBoton(jButton6);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(turnoX == true){
            jButton9.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton9.setEnabled(false);
            desactivarBoton(jButton9);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton9.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton9.setEnabled(false);
            desactivarBoton(jButton9);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(turnoX == true){
            jButton1.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton1.setEnabled(false);
            desactivarBoton(jButton1);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton1.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton1.setEnabled(false);
            desactivarBoton(jButton1);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(turnoX == true){
            jButton2.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton2.setEnabled(false);
            desactivarBoton(jButton2);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton2.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton2.setEnabled(false);
            desactivarBoton(jButton2);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(turnoX == true){
            jButton4.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton4.setEnabled(false);
            desactivarBoton(jButton4);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton4.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton4.setEnabled(false);
            desactivarBoton(jButton4);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(turnoX == true){
            jButton5.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton5.setEnabled(false);
            desactivarBoton(jButton5);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton5.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton5.setEnabled(false);
            desactivarBoton(jButton5);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(turnoX == true){
            jButton7.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton7.setEnabled(false);
            desactivarBoton(jButton7);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton7.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton7.setEnabled(false);
            desactivarBoton(jButton7);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(turnoX == true){
            jButton8.setText("X");
            jLabel2.setText("O");
            jLabel2.setForeground(Color.blue);
            jButton8.setEnabled(false);
            desactivarBoton(jButton8);
            comprobarVictoria();
            turnoX = false;
        }else{
            jButton8.setText("O");
            jLabel2.setText("X");
            jLabel2.setForeground(Color.red);
            jButton8.setEnabled(false);
            desactivarBoton(jButton8);
            comprobarVictoria();
            turnoX = true;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        reset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


    private boolean comprobarVictoria(){
        boolean ganar = false;
        
        if(jButton1.getText().equals("X") && jButton2.getText().equals("X") && jButton3.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton4.getText().equals("X") && jButton5.getText().equals("X") && jButton6.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton7.getText().equals("X") && jButton8.getText().equals("X") && jButton9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton1.getText().equals("O") && jButton2.getText().equals("O") && jButton3.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton4.getText().equals("O") && jButton5.getText().equals("O") && jButton6.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton7.getText().equals("O") && jButton8.getText().equals("O") && jButton9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton1.getText().equals("X") && jButton4.getText().equals("X") && jButton7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton2.getText().equals("X") && jButton5.getText().equals("X") && jButton8.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton3.getText().equals("X") && jButton6.getText().equals("X") && jButton9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton1.getText().equals("O") && jButton4.getText().equals("O") && jButton7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton2.getText().equals("O") && jButton5.getText().equals("O") && jButton8.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton3.getText().equals("O") && jButton6.getText().equals("O") && jButton9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton1.getText().equals("X") && jButton5.getText().equals("X") && jButton9.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton3.getText().equals("X") && jButton5.getText().equals("X") && jButton7.getText().equals("X")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador X!","Victoria X",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton1.getText().equals("O") && jButton5.getText().equals("O") && jButton9.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        if(jButton3.getText().equals("O") && jButton5.getText().equals("O") && jButton7.getText().equals("O")){
            JOptionPane.showMessageDialog(this, "¡Ha ganado Jugador O!","Victoria O",JOptionPane.INFORMATION_MESSAGE);
            ganar = true;
        }
        
        
        if(!jButton1.isEnabled()  && !jButton2.isEnabled() && !jButton3.isEnabled() && !jButton4.isEnabled() && !jButton5.isEnabled() && !jButton6.isEnabled() 
                && !jButton7.isEnabled() && !jButton8.isEnabled() && !jButton9.isEnabled() && !ganar){
            JOptionPane.showMessageDialog(this, "Habéis empatado.","Empate", JOptionPane.INFORMATION_MESSAGE);
        } 
        
        if(ganar == true){
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                jButton6.setEnabled(false);
                jButton7.setEnabled(false);
                jButton8.setEnabled(false);
                jButton9.setEnabled(false);
            }
        
        return ganar;
    }
    
    private void desactivarBoton(JButton button){
        button.setEnabled(false);
        if(button.getText().equals("X")){
            button.setForeground(Color.red);
            button.setFont(new Font("Arial", Font.BOLD, 24));
        }else{
            button.setForeground(Color.blue);
            button.setFont(new Font("Arial", Font.BOLD, 24));
        }
    }
    
    private void reset(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
    }
    
}
