package datos;
// Generated 9 dic 2024, 22:52:13 by Hibernate Tools 6.5.1.Final

import java.math.BigInteger;

/**
 * ResumenCamisetasId generated by hbm2java
 */
public class ResumenCamisetasId implements java.io.Serializable {

	private BigInteger codigocamiseta;
	private BigInteger codigociclista;
	private BigInteger codigoequipo;

	public ResumenCamisetasId() {
	}

	public ResumenCamisetasId(BigInteger codigocamiseta, BigInteger codigociclista, BigInteger codigoequipo) {
		this.codigocamiseta = codigocamiseta;
		this.codigociclista = codigociclista;
		this.codigoequipo = codigoequipo;
	}

	public BigInteger getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(BigInteger codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public BigInteger getCodigociclista() {
		return this.codigociclista;
	}

	public void setCodigociclista(BigInteger codigociclista) {
		this.codigociclista = codigociclista;
	}

	public BigInteger getCodigoequipo() {
		return this.codigoequipo;
	}

	public void setCodigoequipo(BigInteger codigoequipo) {
		this.codigoequipo = codigoequipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResumenCamisetasId))
			return false;
		ResumenCamisetasId castOther = (ResumenCamisetasId) other;

		return ((this.getCodigocamiseta() == castOther.getCodigocamiseta())
				|| (this.getCodigocamiseta() != null && castOther.getCodigocamiseta() != null
						&& this.getCodigocamiseta().equals(castOther.getCodigocamiseta())))
				&& ((this.getCodigociclista() == castOther.getCodigociclista())
						|| (this.getCodigociclista() != null && castOther.getCodigociclista() != null
								&& this.getCodigociclista().equals(castOther.getCodigociclista())))
				&& ((this.getCodigoequipo() == castOther.getCodigoequipo())
						|| (this.getCodigoequipo() != null && castOther.getCodigoequipo() != null
								&& this.getCodigoequipo().equals(castOther.getCodigoequipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigocamiseta() == null ? 0 : this.getCodigocamiseta().hashCode());
		result = 37 * result + (getCodigociclista() == null ? 0 : this.getCodigociclista().hashCode());
		result = 37 * result + (getCodigoequipo() == null ? 0 : this.getCodigoequipo().hashCode());
		return result;
	}

}
