/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Tarde
 */
public class SeleccionPJ extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionPJ
     */
    public SeleccionPJ() {
        initComponents();
        jPanel1.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagen1 = new jpanelimagen.JPanelImagen();
        jLabelSeleccion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonLuffy = new javax.swing.JButton();
        jButtonIchigo = new javax.swing.JButton();
        jButtonSteve = new javax.swing.JButton();
        jButtonKazuya = new javax.swing.JButton();
        jButtonNaruto = new javax.swing.JButton();
        jButtonJin = new javax.swing.JButton();
        jButtonSasuke = new javax.swing.JButton();
        jButtonVegetto = new javax.swing.JButton();
        jButtonLuigi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelImagen1.setImagenfondo(new jpanelimagen.ImagenFondo(new java.io.File("C:/Users/Tarde/Documents/2DAM/DESARROLLO DE INTERFACES/UT3/Fondo De Pantalla Para Iphone.jpg"), 0.5f));

        jLabelSeleccion.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jLabelSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccion.setText("Selecciona tu personaje:");

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jButtonLuffy.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLuffy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg.png"))); // NOI18N
        jButtonLuffy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuffyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLuffy);

        jButtonIchigo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIchigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (1).png"))); // NOI18N
        jButtonIchigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIchigoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIchigo);

        jButtonSteve.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSteve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (2).png"))); // NOI18N
        jButtonSteve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSteveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSteve);

        jButtonKazuya.setBackground(new java.awt.Color(0, 0, 0));
        jButtonKazuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (3).png"))); // NOI18N
        jButtonKazuya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKazuyaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKazuya);

        jButtonNaruto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNaruto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (5).png"))); // NOI18N
        jButtonNaruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNarutoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNaruto);

        jButtonJin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (4).png"))); // NOI18N
        jButtonJin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJinActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJin);

        jButtonSasuke.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSasuke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (6).png"))); // NOI18N
        jButtonSasuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSasukeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSasuke);

        jButtonVegetto.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVegetto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (8).png"))); // NOI18N
        jButtonVegetto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVegettoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVegetto);

        jButtonLuigi.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLuigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/pngegg (7).png"))); // NOI18N
        jButtonLuigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuigiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLuigi);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 120)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("?");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanelImagen1Layout = new javax.swing.GroupLayout(jPanelImagen1);
        jPanelImagen1.setLayout(jPanelImagen1Layout);
        jPanelImagen1Layout.setHorizontalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagen1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabelSeleccion)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagen1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanelImagen1Layout.setVerticalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagen1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImagen1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelImagen1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLuffyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuffyActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg.png")));
    }//GEN-LAST:event_jButtonLuffyActionPerformed

    private void jButtonIchigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIchigoActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (1).png")));
    }//GEN-LAST:event_jButtonIchigoActionPerformed

    private void jButtonSteveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSteveActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (2).png")));
    }//GEN-LAST:event_jButtonSteveActionPerformed

    private void jButtonKazuyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKazuyaActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (3).png")));
    }//GEN-LAST:event_jButtonKazuyaActionPerformed

    private void jButtonNarutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNarutoActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (5).png")));
    }//GEN-LAST:event_jButtonNarutoActionPerformed

    private void jButtonJinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJinActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (4).png")));
    }//GEN-LAST:event_jButtonJinActionPerformed

    private void jButtonSasukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSasukeActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (6).png")));
    }//GEN-LAST:event_jButtonSasukeActionPerformed

    private void jButtonVegettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVegettoActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (8).png")));
    }//GEN-LAST:event_jButtonVegettoActionPerformed

    private void jButtonLuigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuigiActionPerformed
        jLabel1.setText("");
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/gui/imgs/pngegg (7).png")));
    }//GEN-LAST:event_jButtonLuigiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIchigo;
    private javax.swing.JButton jButtonJin;
    private javax.swing.JButton jButtonKazuya;
    private javax.swing.JButton jButtonLuffy;
    private javax.swing.JButton jButtonLuigi;
    private javax.swing.JButton jButtonNaruto;
    private javax.swing.JButton jButtonSasuke;
    private javax.swing.JButton jButtonSteve;
    private javax.swing.JButton jButtonVegetto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSeleccion;
    private javax.swing.JPanel jPanel1;
    private jpanelimagen.JPanelImagen jPanelImagen1;
    // End of variables declaration//GEN-END:variables
}
