/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Tarde
 */
public class PantallaPulsacion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPulsacion
     */
    public PantallaPulsacion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTextoColor = new javax.swing.JLabel();
        jLabelTextoColor2 = new javax.swing.JLabel();
        jButtonMousePressed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTextoColor.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabelTextoColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoColor.setText("TEXTO QUE CAMBIA DE COLOR AL ENTRAR Y SALIR DE EL");
        jLabelTextoColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTextoColorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTextoColorMouseExited(evt);
            }
        });

        jLabelTextoColor2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabelTextoColor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoColor2.setText("TEXTO QUE CAMBIA DE COLOR AL PULSARLO Y DEJARLO DE PULSAR");
        jLabelTextoColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTextoColor2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelTextoColor2MouseReleased(evt);
            }
        });

        jButtonMousePressed.setText("MousePressed");
        jButtonMousePressed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMousePressedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonMousePressedMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTextoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTextoColor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButtonMousePressed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabelTextoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTextoColor2)
                .addGap(55, 55, 55)
                .addComponent(jButtonMousePressed)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTextoColorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoColorMouseEntered
        jLabelTextoColor.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabelTextoColorMouseEntered

    private void jLabelTextoColorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoColorMouseExited
        jLabelTextoColor.setForeground(Color.red);
    }//GEN-LAST:event_jLabelTextoColorMouseExited

    private void jLabelTextoColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoColor2MouseClicked
        jLabelTextoColor2.setForeground(Color.blue);
    }//GEN-LAST:event_jLabelTextoColor2MouseClicked

    private void jLabelTextoColor2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTextoColor2MouseReleased
        jLabelTextoColor2.setForeground(Color.green);
    }//GEN-LAST:event_jLabelTextoColor2MouseReleased

    private void jButtonMousePressedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMousePressedMousePressed
        jLabelTextoColor.setForeground(Color.black);
        jLabelTextoColor2.setForeground(Color.black);
    }//GEN-LAST:event_jButtonMousePressedMousePressed

    private void jButtonMousePressedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMousePressedMouseReleased
        jLabelTextoColor.setForeground(Color.cyan);
        jLabelTextoColor2.setForeground(Color.cyan);
    }//GEN-LAST:event_jButtonMousePressedMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPulsacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPulsacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPulsacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPulsacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPulsacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMousePressed;
    private javax.swing.JLabel jLabelTextoColor;
    private javax.swing.JLabel jLabelTextoColor2;
    // End of variables declaration//GEN-END:variables
}
