/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//Importamos la función color para establecer el color del fondo de la interfaz.
import java.awt.Color;
//Importamos la función JOptionPane para lanzar mensajes en una nueva ventana al usuario.
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Sánchez Gil
 */
public class PantallaInicial extends javax.swing.JFrame {

    //Creamos la variable entera contador.
    int contador;
    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicial() {
        initComponents();
        //De nuevo, seleccionamos el ContentPane del layout "PantallaInicial" para cambiarle el fondo.
        getContentPane().setBackground(new java.awt.Color(12,82,83));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgMates = new javax.swing.ButtonGroup();
        btgPlanetas = new javax.swing.ButtonGroup();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        btgOrtografia = new javax.swing.ButtonGroup();
        btgListo = new javax.swing.ButtonGroup();
        txtTitulo = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JLabel();
        txtOperacion = new javax.swing.JLabel();
        rbt51 = new javax.swing.JRadioButton();
        rbt45 = new javax.swing.JRadioButton();
        rbt56 = new javax.swing.JRadioButton();
        rbt31 = new javax.swing.JRadioButton();
        txtPlanetas = new javax.swing.JLabel();
        rbtMarte = new javax.swing.JRadioButton();
        rbtJupiter = new javax.swing.JRadioButton();
        rbtTierra = new javax.swing.JRadioButton();
        rbtSaturno = new javax.swing.JRadioButton();
        txtOrtografia = new javax.swing.JLabel();
        rbtDesicion = new javax.swing.JRadioButton();
        rbtHay = new javax.swing.JRadioButton();
        rbtAhi = new javax.swing.JRadioButton();
        rbtOla = new javax.swing.JRadioButton();
        txtListo = new javax.swing.JLabel();
        ckbSagaz = new javax.swing.JCheckBox();
        ckbListo = new javax.swing.JCheckBox();
        ckbLerdo = new javax.swing.JCheckBox();
        ckbAstuto = new javax.swing.JCheckBox();
        txtValor1 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JLabel();
        txtValor3 = new javax.swing.JLabel();
        txtValor4 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        jRadioButton13.setText("desición");

        jRadioButton14.setText("hay");

        jRadioButton15.setText("ahí");

        jRadioButton16.setText("ola");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(222, 222, 222));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("TEST DE IQ");

        txtSubtitulo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSubtitulo.setForeground(new java.awt.Color(222, 222, 222));
        txtSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSubtitulo.setText("Responde a las siguientes preguntas:");

        txtOperacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(222, 222, 222));
        txtOperacion.setText("4*6+3+2*2=");

        btgMates.add(rbt51);
        rbt51.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbt51.setForeground(new java.awt.Color(222, 222, 222));
        rbt51.setText("51");
        rbt51.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbt51.setMaximumSize(new java.awt.Dimension(60, 60));
        rbt51.setMinimumSize(new java.awt.Dimension(60, 60));
        rbt51.setPreferredSize(new java.awt.Dimension(70, 30));
        rbt51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt51ActionPerformed(evt);
            }
        });

        btgMates.add(rbt45);
        rbt45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbt45.setForeground(new java.awt.Color(222, 222, 222));
        rbt45.setText("45");
        rbt45.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbt45.setMaximumSize(new java.awt.Dimension(60, 60));
        rbt45.setMinimumSize(new java.awt.Dimension(60, 60));
        rbt45.setPreferredSize(new java.awt.Dimension(70, 30));

        btgMates.add(rbt56);
        rbt56.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbt56.setForeground(new java.awt.Color(222, 222, 222));
        rbt56.setText("56");
        rbt56.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbt56.setMaximumSize(new java.awt.Dimension(60, 60));
        rbt56.setMinimumSize(new java.awt.Dimension(60, 60));
        rbt56.setPreferredSize(new java.awt.Dimension(70, 30));

        btgMates.add(rbt31);
        rbt31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbt31.setForeground(new java.awt.Color(222, 222, 222));
        rbt31.setText("31");
        rbt31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbt31.setMaximumSize(new java.awt.Dimension(60, 60));
        rbt31.setMinimumSize(new java.awt.Dimension(60, 60));
        rbt31.setPreferredSize(new java.awt.Dimension(70, 30));
        rbt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt31ActionPerformed(evt);
            }
        });

        txtPlanetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPlanetas.setForeground(new java.awt.Color(222, 222, 222));
        txtPlanetas.setText("Nombre del quinto planeta");

        btgPlanetas.add(rbtMarte);
        rbtMarte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtMarte.setForeground(new java.awt.Color(222, 222, 222));
        rbtMarte.setText("Marte");
        rbtMarte.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtMarte.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtMarte.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtMarte.setPreferredSize(new java.awt.Dimension(70, 30));
        rbtMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMarteActionPerformed(evt);
            }
        });

        btgPlanetas.add(rbtJupiter);
        rbtJupiter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtJupiter.setForeground(new java.awt.Color(222, 222, 222));
        rbtJupiter.setText("Júpiter");
        rbtJupiter.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtJupiter.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtJupiter.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtJupiter.setPreferredSize(new java.awt.Dimension(70, 30));

        btgPlanetas.add(rbtTierra);
        rbtTierra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtTierra.setForeground(new java.awt.Color(222, 222, 222));
        rbtTierra.setText("Tierra");
        rbtTierra.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtTierra.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtTierra.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtTierra.setPreferredSize(new java.awt.Dimension(70, 30));

        btgPlanetas.add(rbtSaturno);
        rbtSaturno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtSaturno.setForeground(new java.awt.Color(222, 222, 222));
        rbtSaturno.setText("Saturno");
        rbtSaturno.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtSaturno.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtSaturno.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtSaturno.setPreferredSize(new java.awt.Dimension(70, 30));

        txtOrtografia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtOrtografia.setForeground(new java.awt.Color(222, 222, 222));
        txtOrtografia.setText("Palabra con error ortográfico");

        btgOrtografia.add(rbtDesicion);
        rbtDesicion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtDesicion.setForeground(new java.awt.Color(222, 222, 222));
        rbtDesicion.setText("desición");
        rbtDesicion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtDesicion.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtDesicion.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtDesicion.setPreferredSize(new java.awt.Dimension(70, 30));

        btgOrtografia.add(rbtHay);
        rbtHay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtHay.setForeground(new java.awt.Color(222, 222, 222));
        rbtHay.setText("hay");
        rbtHay.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtHay.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtHay.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtHay.setPreferredSize(new java.awt.Dimension(70, 30));

        btgOrtografia.add(rbtAhi);
        rbtAhi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtAhi.setForeground(new java.awt.Color(222, 222, 222));
        rbtAhi.setText("ahí");
        rbtAhi.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtAhi.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtAhi.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtAhi.setPreferredSize(new java.awt.Dimension(70, 30));

        btgOrtografia.add(rbtOla);
        rbtOla.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtOla.setForeground(new java.awt.Color(222, 222, 222));
        rbtOla.setText("ola");
        rbtOla.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbtOla.setMaximumSize(new java.awt.Dimension(60, 60));
        rbtOla.setMinimumSize(new java.awt.Dimension(60, 60));
        rbtOla.setPreferredSize(new java.awt.Dimension(70, 30));
        rbtOla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOlaActionPerformed(evt);
            }
        });

        txtListo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtListo.setForeground(new java.awt.Color(222, 222, 222));
        txtListo.setText("Sinónimos de inteligente");

        ckbSagaz.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ckbSagaz.setForeground(new java.awt.Color(222, 222, 222));
        ckbSagaz.setText("sagaz");
        ckbSagaz.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ckbSagaz.setMaximumSize(new java.awt.Dimension(60, 60));
        ckbSagaz.setMinimumSize(new java.awt.Dimension(60, 60));
        ckbSagaz.setPreferredSize(new java.awt.Dimension(70, 30));
        ckbSagaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSagazActionPerformed(evt);
            }
        });

        ckbListo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ckbListo.setForeground(new java.awt.Color(222, 222, 222));
        ckbListo.setText("listo");
        ckbListo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ckbListo.setMaximumSize(new java.awt.Dimension(60, 60));
        ckbListo.setMinimumSize(new java.awt.Dimension(60, 60));
        ckbListo.setPreferredSize(new java.awt.Dimension(70, 30));

        ckbLerdo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ckbLerdo.setForeground(new java.awt.Color(222, 222, 222));
        ckbLerdo.setText("lerdo");
        ckbLerdo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ckbLerdo.setMaximumSize(new java.awt.Dimension(60, 60));
        ckbLerdo.setMinimumSize(new java.awt.Dimension(60, 60));
        ckbLerdo.setPreferredSize(new java.awt.Dimension(70, 30));

        ckbAstuto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ckbAstuto.setForeground(new java.awt.Color(222, 222, 222));
        ckbAstuto.setText("astuto");
        ckbAstuto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ckbAstuto.setMaximumSize(new java.awt.Dimension(60, 60));
        ckbAstuto.setMinimumSize(new java.awt.Dimension(60, 60));
        ckbAstuto.setPreferredSize(new java.awt.Dimension(70, 30));

        txtValor1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtValor1.setForeground(new java.awt.Color(222, 222, 222));
        txtValor1.setText("valor");

        txtValor2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtValor2.setForeground(new java.awt.Color(222, 222, 222));
        txtValor2.setText("valor");

        txtValor3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtValor3.setForeground(new java.awt.Color(222, 222, 222));
        txtValor3.setText("valor");

        txtValor4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtValor4.setForeground(new java.awt.Color(222, 222, 222));
        txtValor4.setText("valor");

        btnMostrar.setBackground(new java.awt.Color(12, 22, 23));
        btnMostrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(222, 222, 222));
        btnMostrar.setText("¡Resultados!");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlanetas)
                    .addComponent(txtOrtografia)
                    .addComponent(txtListo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtMarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtOla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbSagaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbt45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbtJupiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbtDesicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rbt56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtTierra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbt31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbtSaturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rbtHay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckbLerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ckbAstuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtAhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(ckbListo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtValor4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtValor3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtValor1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperacion)
                    .addComponent(rbt51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbt31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlanetas)
                    .addComponent(rbtMarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtJupiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtTierra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtSaturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrtografia)
                    .addComponent(rbtOla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtDesicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtHay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtAhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListo)
                    .addComponent(ckbSagaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbListo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbLerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbAstuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor4))
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt51ActionPerformed

    private void rbt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt31ActionPerformed

    private void rbtMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMarteActionPerformed

    private void rbtOlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtOlaActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void ckbSagazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSagazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSagazActionPerformed
//Método que se ejecutará una vez que pulsemos el botón "btnMostrar".
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //Inicializa a 0 la variable contador que hemos creado anteriormente.
        contador=0;
        //Condición que comprueba si el radioButton de nombre "rbt31" está seleccionado, con la función "isSelected()".
        if(rbt31.isSelected()){
            //En caso de que se cumpla, le añade al contador 1.
            contador+=1;
            //Establece el valor del label txtValor1 a "CORRECTO" y cambia el color de su fuente a verde, esto lo hacemos con las funciones "setText()" y "setForeground"
            //respectivamente.
            txtValor1.setText("CORRECTO");
            txtValor1.setForeground(Color.green);
        //En caso contrario:
        }else{
            //Establece dicho valor a "INCORRECTO" y su color a rojo.
            txtValor1.setText("INCORRECTO");
            txtValor1.setForeground(Color.red);
        }
        //Realiza lo mismo para cada una de las 3 preguntas restantes, en este caso comprueba que el botón seleccionado sea rbtJupiter, que es la respuesta correcta
        //y realiza lo mismo que la función anterior. 
        if(rbtJupiter.isSelected()){
            contador+=1;
            txtValor2.setText("CORRECTO");
            txtValor2.setForeground(Color.green);
        }else{
            txtValor2.setText("INCORRECTO");
            txtValor2.setForeground(Color.red);
        }
        //Lo mismo con "desición".
        if(rbtDesicion.isSelected()){
            contador+=1;
            txtValor3.setText("CORRECTO");
            txtValor3.setForeground(Color.green);
        }else{
            txtValor3.setText("INCORRECTO");
            txtValor3.setForeground(Color.red);
        }
        //En el caso de las variables checkbox comprueba que las 3 que son correctas estén seleccionadas antes de darla omo correcta.
        if(ckbAstuto.isSelected() && ckbListo.isSelected() && ckbSagaz.isSelected()){
            //Aquí comrpueba si el usuario a seleccionado también la variable de la checkbox "ckbLerdo", en caso de que no, marca como correcta la respuesta.
            if(!ckbLerdo.isSelected()){
                contador+=1;
                txtValor4.setText("CORRECTO");
                txtValor4.setForeground(Color.green);
            }else{
                txtValor4.setText("INCORRECTO");
                txtValor4.setForeground(Color.red);
            }
        }else{
            txtValor4.setText("INCORRECTO");
            txtValor4.setForeground(Color.red);
        }
        //Finalmente como añadido, el programa cuenta cuantas respuestas correctas ha tenido el usuario y "mide" su IQ en base a las respuestas proporcionadas.
        //Esto lo he realizado igulando el contador a un valor entre 0 y 4 y mostrando un mensaje en una ventana nueva utilizando la función
        //JOptionPane.showMessageDialog para indicarle los resultados
        if(contador==0){
            JOptionPane.showMessageDialog(this, "IQ NEGATIVO 0/4 RESPUESTAS CORRECTAS");
        }
        
        if(contador==1){
            JOptionPane.showMessageDialog(this, "IQ 50 1/4 RESPUESTAS CORRECTAS");
        }
        
        if(contador==2){
            JOptionPane.showMessageDialog(this, "IQ 75 2/4 RESPUESTAS CORRECTAS");
        }
        
        if(contador==3){
            JOptionPane.showMessageDialog(this, "IQ 90 3/4 RESPUESTAS CORRECTAS");
        }
        
        if(contador==4){
            JOptionPane.showMessageDialog(this, "IQ 120 4/4 RESPUESTAS CORRECTAS");
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgListo;
    private javax.swing.ButtonGroup btgMates;
    private javax.swing.ButtonGroup btgOrtografia;
    private javax.swing.ButtonGroup btgPlanetas;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox ckbAstuto;
    private javax.swing.JCheckBox ckbLerdo;
    private javax.swing.JCheckBox ckbListo;
    private javax.swing.JCheckBox ckbSagaz;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton rbt31;
    private javax.swing.JRadioButton rbt45;
    private javax.swing.JRadioButton rbt51;
    private javax.swing.JRadioButton rbt56;
    private javax.swing.JRadioButton rbtAhi;
    private javax.swing.JRadioButton rbtDesicion;
    private javax.swing.JRadioButton rbtHay;
    private javax.swing.JRadioButton rbtJupiter;
    private javax.swing.JRadioButton rbtMarte;
    private javax.swing.JRadioButton rbtOla;
    private javax.swing.JRadioButton rbtSaturno;
    private javax.swing.JRadioButton rbtTierra;
    private javax.swing.JLabel txtListo;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtOrtografia;
    private javax.swing.JLabel txtPlanetas;
    private javax.swing.JLabel txtSubtitulo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtValor1;
    private javax.swing.JLabel txtValor2;
    private javax.swing.JLabel txtValor3;
    private javax.swing.JLabel txtValor4;
    // End of variables declaration//GEN-END:variables
}
