/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;

/**
 *
 * @author Tarde
 */
public class PantallaInicial extends javax.swing.JFrame {
    int contador=0;
    /** Creates new form PantallaInicial */
    public PantallaInicial() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(131, 105, 83));
        jPanel1.setBackground(new java.awt.Color(131, 105, 83));
        jPanel2.setBackground(new java.awt.Color(131, 105, 83));
        jPanel3.setBackground(new java.awt.Color(131, 105, 83));
        jLabelHexagono.setVisible(false);
        jLabelRombo.setVisible(false);
        jLabelTriangulo.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFigura = new javax.swing.ButtonGroup();
        buttonGroupColor = new javax.swing.ButtonGroup();
        jButtonConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCuadrado = new javax.swing.JLabel();
        jLabelTriangulo = new javax.swing.JLabel();
        jLabelRombo = new javax.swing.JLabel();
        jLabelHexagono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonCuadrado = new javax.swing.JRadioButton();
        jRadioButtonRombo = new javax.swing.JRadioButton();
        jRadioButtonHexagono = new javax.swing.JRadioButton();
        jRadioButtonTriangulo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jRadioButtonAzul = new javax.swing.JRadioButton();
        jRadioButtonAmarillo = new javax.swing.JRadioButton();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jLabelSalida = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConfirmar.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabelCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/cuadrado.png"))); // NOI18N
        jPanel1.add(jLabelCuadrado, "card2");

        jLabelTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/triangulo.png"))); // NOI18N
        jPanel1.add(jLabelTriangulo, "card3");

        jLabelRombo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/rombo.png"))); // NOI18N
        jPanel1.add(jLabelRombo, "card4");

        jLabelHexagono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHexagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imgs/hexagono.png"))); // NOI18N
        jPanel1.add(jLabelHexagono, "card5");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroupFigura.add(jRadioButtonCuadrado);
        jRadioButtonCuadrado.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonCuadrado.setText("Cuadrado");
        jPanel2.add(jRadioButtonCuadrado);

        buttonGroupFigura.add(jRadioButtonRombo);
        jRadioButtonRombo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonRombo.setText("Rombo");
        jPanel2.add(jRadioButtonRombo);

        buttonGroupFigura.add(jRadioButtonHexagono);
        jRadioButtonHexagono.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonHexagono.setText("Hexagono");
        jRadioButtonHexagono.setActionCommand("Hexágono");
        jPanel2.add(jRadioButtonHexagono);

        buttonGroupFigura.add(jRadioButtonTriangulo);
        jRadioButtonTriangulo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonTriangulo.setText("Triángulo");
        jPanel2.add(jRadioButtonTriangulo);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroupColor.add(jRadioButtonVerde);
        jRadioButtonVerde.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonVerde.setText("Verde");
        jPanel3.add(jRadioButtonVerde);

        buttonGroupColor.add(jRadioButtonAzul);
        jRadioButtonAzul.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonAzul.setText("Azul");
        jPanel3.add(jRadioButtonAzul);

        buttonGroupColor.add(jRadioButtonAmarillo);
        jRadioButtonAmarillo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonAmarillo.setText("Amarillo");
        jPanel3.add(jRadioButtonAmarillo);

        buttonGroupColor.add(jRadioButtonRojo);
        jRadioButtonRojo.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jRadioButtonRojo.setText("Rojo");
        jPanel3.add(jRadioButtonRojo);

        jLabelSalida.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabelSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("DESCRIBE LA FIGURA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmar)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        if(contador==0){
            if(jRadioButtonCuadrado.isSelected() && jRadioButtonVerde.isSelected()){
                jLabelCuadrado.setVisible(false);
                jLabelTriangulo.setVisible(true);
                jLabelSalida.setText("¡Correcto!");
                jLabelSalida.setForeground(Color.green);
                contador++;
            }else{
                jLabelSalida.setText("¡Incorrecto, fijate bien!");
                jLabelSalida.setForeground(Color.red);
            }
            
        }
        else if(contador==1){
            if(jRadioButtonTriangulo.isSelected() && jRadioButtonAzul.isSelected()){
                jLabelTriangulo.setVisible(false);
                jLabelRombo.setVisible(true);
                jLabelSalida.setText("¡Correcto!");
                jLabelSalida.setForeground(Color.green);
                contador++;
            }else{
                jLabelSalida.setText("¡Incorrecto, fijate bien!");
                jLabelSalida.setForeground(Color.red);
            }
        }
        else if(contador==2){
            if(jRadioButtonRombo.isSelected() && jRadioButtonAmarillo.isSelected()){
                jLabelRombo.setVisible(false);
                jLabelHexagono.setVisible(true);
                jLabelSalida.setText("¡Correcto!"); 
                jLabelSalida.setForeground(Color.green);
                contador++;
            }else{
                jLabelSalida.setText("¡Incorrecto, fijate bien!");
                jLabelSalida.setForeground(Color.red);
            }
        }
        else if(contador==3){
            if(jRadioButtonHexagono.isSelected() && jRadioButtonRojo.isSelected()){
                jPanel1.setVisible(false);
                jLabelSalida.setText("¡Correcto!");
                jLabelSalida.setForeground(Color.green);
                contador++;
                jRadioButtonCuadrado.setEnabled(false);
                jRadioButtonRombo.setEnabled(false);
                jRadioButtonHexagono.setEnabled(false);
                jRadioButtonTriangulo.setEnabled(false);
                jRadioButtonVerde.setEnabled(false);
                jRadioButtonAzul.setEnabled(false);
                jRadioButtonAmarillo.setEnabled(false);
                jRadioButtonRojo.setEnabled(false);
                jButtonConfirmar.setEnabled(false);
            }else{
                jLabelSalida.setText("¡Incorrecto, fijate bien!");
                jLabelSalida.setForeground(Color.red);
            }
        }
          
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupFigura;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelCuadrado;
    private javax.swing.JLabel jLabelHexagono;
    private javax.swing.JLabel jLabelRombo;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTriangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonAmarillo;
    private javax.swing.JRadioButton jRadioButtonAzul;
    private javax.swing.JRadioButton jRadioButtonCuadrado;
    private javax.swing.JRadioButton jRadioButtonHexagono;
    private javax.swing.JRadioButton jRadioButtonRojo;
    private javax.swing.JRadioButton jRadioButtonRombo;
    private javax.swing.JRadioButton jRadioButtonTriangulo;
    private javax.swing.JRadioButton jRadioButtonVerde;
    // End of variables declaration//GEN-END:variables

}
